### ISSUE TITLE
Регистрация

### ISSUE THREAD

**Issue by lozovich88** [loza-life/loza-server#1]
Не работает регистрация, или что то не то, с настройками сервера 
метод: /api/signup
Лог с сервера:
{"time":"2024-07-21T18:08:50.912636+03:00","id":"","remote_ip":"::1","host":"localhost:8080","method":"POST","uri":"/api/signup","user_agent":"PostmanRuntime/7.37.3","status":400,"error":"code=400, message=missing or malformed jwt","latency":155625,"latency_human":"155.625µs","bytes_in":62,"bytes_out":39}

**Comment by sea5kg** [comment]
Попробовал сделать запрос:

```
import requests

url_signup = "http://localhost:8080/api/signup"
data_signup = {
    'name': 'testuser',
    'password': 'testuser',
}

resp = requests.post(url_signup, json=data_signup)
```

в ответ получил:
```
StatusCode: 400
{"message":"missing or malformed jwt"}
```

Надо где то найти jwt токен либо хендлер сломан

**Comment by sea5kg** [comment]
надо вызывать не `/api/signup` а  `/auth/signup` и тогда будет все ок
